from A.py import A()
from B.py import B()
from C.py import C()
from D.py import D()
from E.py import E()
from F.py import F()
from G.py import G()
from H.py import H()
from I.py import I()
from J.py import J()
from K.py import K()
from L.py import L()
from M.py import M()
from N.py import N()
from O.py import O()
from P.py import P()
from Q.py import Q()
from R.py import R()
from S.py import S()
from T.py import T()
from U.py import U()
from V.py import V()
from W.py import W()
from X.py import X()
from Z.py import Z()
from Espace.py import Espace()

dictionnaireFonctions = {'a': A, 'b': B, 'c': C, 'd': D, 'e': E, 'f': F, 'g': G, 'h': H, 'i': I, 'j': J, 'k': K, 'l': L, 'm': M, 'n': N, 'o': O, 'p': P, 'q': Q, 'r': R, 's': S, 't': T, 'u': U, 'v': V, 'w': W, 'x': X, 'y': Y, 'z': Z, ' ': Espace}

message = input('Que voulez-vous dire ?')

for character in message:
	fonction = dictionnaireFonctions.get(character)
	fonction()